shell: formalise bookmarking

diff --git a/shell/.config/shell/general.d/20-aliases b/shell/.config/shell/general.d/20-aliases
--- a/shell/.config/shell/general.d/20-aliases
+++ b/shell/.config/shell/general.d/20-aliases
@@ -30,9 +30,10 @@ cdl() {
 }
 alias c="cdl"
 
+# mnemonic: l = long, a = all, b = bytes
+alias l="ls"
 alias ll="ls -lh"
 alias la="ls -lAh"
-alias l="ls"
 alias lb="ls -la"
 
 alias g="git"
@@ -41,11 +42,35 @@ alias vim="nvim"
 alias v="vim"
 alias cm="git commit -m"
 
-# cdl to a shortcutted directory (in ~/sh)
+SHELLMARK_DIR="$HOME"/sh
+# cdl to a shortcutted directory
 shcdl() {
-    cdl ~/sh/"$1"
+    cdl "$SHELLMARK_DIR/$1"
 }
 alias s="shcdl"
+
+# bookmark a file
+# bookmarks are absolute symlinks in a bookmarks folder, optionally foldered
+# further
+# (wanted to allow relative symlinks, but that makes foldering difficult)
+shcdl-ln() {
+    if [[ $# != 1 && $# != 2 ]]; then
+        echo >&2 "error: expected exactly 1 or 2 arguments (got $#)"
+        return 1
+    fi
+    target="$1"
+
+    # get link name, create any required directories
+    if [[ $# == 2 ]]; then
+        link_name="$2"
+    else
+        link_name="$(basename "$target")"
+    fi
+    mkdir -p "$(dirname "$SHELLMARK_DIR/$link_name")"
+
+    target="$(realpath "$target")"
+    ln -s "$target" "$SHELLMARK_DIR/$link_name"
+}
 
 # quicker 'date now' command
 alias d="date +%F"
